version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
    depends_on:
      - sqlserver
      - mongodb
      - rabbitmq
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

volumes:
  sqlserverdata:
  mongodbdata:
